version: "3.9" # format <=> docker engine version <=> docker-compose version

networks:
  mal:

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - mal
    ports:
      - 27017:27017
    volumes:
      - /data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    networks:
      - mal
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin

  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    networks:
      - mal
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /data/neo4j:/data

  mal_backend:
    image: mal_backend
    container_name: mal_backend
    restart: always
    networks:
      - mal
    depends_on:
      - mongo
      - neo4j
    ports:
      - 5000:5000
